version: '3.7'

services:

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile 
    ports:
      - 5001:5000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - webapp      


